---
kind: Service
apiVersion: v1
metadata:
  name: employee-service
spec:
  selector:
     # Should match the template.metadata.labels.app value
    app: employee
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 7003
      # Port to forward to inside the pod
      targetPort: 7003
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  selector:
    matchLabels:
        app: employee
  replicas: 1
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: prashantdocker87/employee:one
          #same port as mentioned in applciations application.properties
          ports:
            - containerPort: 7003