
oauth2:
  server: 
     uri: ${OAUTH_SERVER_URI:http://localhost:7777/oauth/}
  clients:
     clientDetails:
        -
           clientId: employee
           clientSecret: secret
        -
           clientId: defg
           clientSecret: 1234
           
  
