---
kind: Service
apiVersion: v1
metadata:
  name: auth-server-service
spec:
  selector:
    # Should match the template.metadata.labels.app value
    app: oauth-server
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 80
      # Port to forward to inside the pod
      targetPort: 7777
      # Port accessible outside cluster
      nodePort: 30001
      name: http
  type: NodePort



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-server-deployment
spec:
  selector:
    matchLabels:
        app: oauth-server
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth-server
    spec:
      containers:
        - name: oauth-server
          image: prashantdocker87/oauth-server:one
          #same port as mentioned in applciations application.properties
          ports:
            - containerPort: 7777
          readinessProbe:
              httpGet:
                path: /actuator/health
                port: 7777
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 3
              failureThreshold: 1
          livenessProbe:
              httpGet:
                path: /actuator/health
                port: 7777
              initialDelaySeconds: 20
              timeoutSeconds: 2
              periodSeconds: 8
              failureThreshold: 1