INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'ROLE_ADMIN');

INSERT INTO AUTHORITY(ID, NAME) VALUES (2, 'ROLE_USER');


INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
VALUES (1, 'john', /*secret*/'$2a$10$krDTAgKDLpHHbzcngFn2suQ/RNyrf7AOLT8WeX5GftzD4cjIv2pv.', FALSE, FALSE, FALSE, TRUE);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
VALUES (2, 'tom',  /*secret*/'$2a$10$krDTAgKDLpHHbzcngFn2suQ/RNyrf7AOLT8WeX5GftzD4cjIv2pv.', FALSE, FALSE, FALSE, TRUE);
  
INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 2);

INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (2, 1);